FROM python:3.13-slim
WORKDIR /app

COPY todo-backend/requirements.txt .
RUN pip install -r requirements.txt

COPY todo-backend/app ./app
COPY todo-backend/run.py .

EXPOSE 8000
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
